<a href="https://colab.research.google.com/github/vicmanw1ld/IA/blob/main/introduccion_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.zeros((2, 4))

a


a.size

8

In [ ]:
a.shape


(2, 4)

In [ ]:
a.ndim

2

In [ ]:
# Array cuyos valores son todos 0
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# Array cuyos valores son todos 1
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# Array cuyos valores son todos el valor indicado como segundo parámetro de la función
np.full((2, 3, 4), 8) # El 8 es el valor que le das por defecto

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [ ]:
# El resultado de np.empty no es predecible
# Inicializa los valores del array con lo que haya en memoria en ese momento
np.empty((2, 3, 9))

array([[[3.15820261e-315, 0.00000000e+000, 6.79823792e-310,
         4.47543482e+217, 6.80648771e+199, 6.19406593e+223,
         1.99108547e+209, 3.76476751e-085, 1.14406376e+243],
        [1.95918563e-027, 1.05923054e-153, 3.60241447e+252,
         1.62691065e+219, 6.36058239e+151, 1.05894327e-153,
         5.03887208e+175, 1.53044312e-094, 3.16046395e+180],
        [7.26588105e+223, 7.29537362e+175, 1.97278832e-153,
         5.97185003e+175, 4.55816195e+257, 2.20892690e+161,
         2.64512473e+185, 2.93305690e+222, 1.43616552e+161]],

       [[1.89130245e+219, 3.99461109e+252, 1.90649515e+185,
         5.04533203e+223, 1.06209545e+248, 8.02675125e-095,
         2.11336376e+214, 1.89122267e+219, 1.96097649e+243],
        [9.10016856e+276, 3.57722603e-057, 1.78935926e+161,
         1.96841819e-153, 4.18001791e+175, 1.28897780e+248,
         8.18434960e-085, 4.50381864e+132, 1.49347735e+214],
        [9.45869679e-154, 9.53728330e-307, 3.91701626e-027,
         3.57755833e+160, 7.10569

In [ ]:
# Inicializacion del array utilizando un array de Python
b = np.array([[1, 2, 3], [4, 5, 6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Creación del array utilizando una función basada en rangos
# (minimo, maximo, número elementos del array)
print(np.linspace(0, 6, 10))

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]


In [ ]:
array_uni = np.array([1,3,5,7,9,11])
print(array_uni.shape)
type(array_uni)


(6,)


numpy.ndarray

In [ ]:
#accediendo al 5 elemento del array
array_uni[5]
#accede al 3 y 4
array_uni[2:4]

#accediendo al elemento 0,3 y 5
array_uni[0::3] #va dando saltos de 3 en 3

array([1, 7])

In [ ]:
#Creando un array multidimensional
array_multi = np.array([[1,2,3,4], [5,6,7,8]])

print(array_multi.shape)
print(array_multi)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#acceder al elemento 3 que es el 4
array_multi[0,3] #fila 0 elemento 3

np.int64(4)

In [ ]:
#accediendo a todos los elementos de la segunda fila
array_multi[1, :]

array([5, 6, 7, 8])

In [ ]:
# acceder al tercer elemento de ambas listas
array_multi[:, 2] #accede a ambas listas y devuelve el elemento 2, con 0:, 2 tambein funciona

array([3, 7])

MODIFICAR UN ARRAY


In [ ]:
#arange para crear arrais con rango
#crea un array unidimensional del 0 al 27
array1 = np.arange(28)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [ ]:
#cambiar las dimensiones del array y sus longitudes
array1.shape = (7, 4) #7 filas 4 columnas
array1 # no se puede poner un array que no encaje

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [ ]:
# Transformar un array
array2 = array1.reshape(4,7) #4 filas 7 columnas
array2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [ ]:
#modificamos el nuevo array2
array2[0, 3] = 20
array2

array([[ 0,  1,  2, 20,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [ ]:
# Vemos que ha cambiado, pero tambien cambia en array1
array1

array([[ 0,  1,  2, 20],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [ ]:
# desenvuelve el array devolviendo un nuevo array de una sola dimensión
# Al loro que es un puntero que apunta al otro por lo que si lo modificamos tambien se modifica
array1.ravel()

array([ 0,  1,  2, 20,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

OPERACIONES ARITMÉTICAS CON ARRAYS


In [ ]:
# Creación de dos Arrays unidimensionales
array1 = np.arange(2, 18, 2)
array2 = np.arange(8)
print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [ 2  4  6  8 10 12 14 16]
Array 2: [0 1 2 3 4 5 6 7]


In [53]:
#sumar
array1 + array2

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [54]:
#resta
array1 - array2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
#multiplicación
array1 * array2

array([  0,   4,  12,  24,  40,  60,  84, 112])

BROADCASTING


In [58]:
#Si se aplican operaciones aritméticas sobre Arrays que no tienen la misma forma
# (shape) Numpy aplica un propiedad que se denomina Broadcasting.

array1 = np.arange(5)
array2 = np.array(3)
print("Shape Array 1:", array1.shape)
print("Array 1:", array1)
print()
print("Shape Array 2:", array2.shape)
print("Array 2:", array2)

Shape Array 1: (5,)
Array 1: [0 1 2 3 4]

Shape Array 2: ()
Array 2: 3


In [59]:
#suma de ambos
array1 + array2

array([3, 4, 5, 6, 7])

In [ ]:
# si que nos lo suma aunq en mates no se puedan sumar arrays de distintas dimensiones
#Lo que hace es duplicar el 3 hasta que suma todos los elementos por 3
# en arrays multidimensionales si los sumas con unidimensional pasa igual, duplica la segunda fila

FUNCIONES ESTADÍSTICAS SOBRE ARRAYS


In [60]:
# Creación de un Array unidimensional
array1 = np.arange(1, 20, 2)
print("Array 1:", array1)

Array 1: [ 1  3  5  7  9 11 13 15 17 19]


In [61]:
# Media de los elementos del Array
array1.mean()

np.float64(10.0)

In [62]:
# Suma de los elementos del Array
array1.sum()

np.int64(100)

In [64]:
dir(array1) # todos los métodos que podemos usar

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '_

In [65]:
help(array1.max) # nos da información sobre los métodos

Help on built-in function max:

max(...) method of numpy.ndarray instance
    a.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
    
    Return the maximum along a given axis.
    
    Refer to `numpy.amax` for full documentation.
    
    See Also
    --------
    numpy.amax : equivalent function



UNIVERSAL FUNCTIONS ufunc

In [66]:
# Cuadrado de los elementos del Array
np.square(array1)

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361])

In [67]:
# Raiz cuadrada de los elementos del Array
np.sqrt(array1)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894])

In [68]:
# Exponencial de los elementos del Array
np.exp(array1)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
       2.41549528e+07, 1.78482301e+08])

In [69]:
# log de los elementos del Array
np.log(array1)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])